### ISSUE TITLE
Single Product Page

### ISSUE THREAD

**Issue by cacelii** [DatGreekChick/glamazonians#32]
GET /products/:productId

## Functions
- [ ] more information on that particular item (product descriptions, photos and reviews)
-  [ ] can add item to cart
-  [ ] can chose quantity to add to cart
 - [ ] can see reviews for that item
 - [ ] has a form to submit a review for that item
 - [ ] can see similar items on tag  link click

**Comment by DatGreekChick** [comment]
CLOSES #32
